export const COPY = {
  pt: {
    title: 'Relatórios de Scrap',
    subtitle: 'Componha, publique e exporte análises rastreáveis.',
    create: 'Novo relatório',
    search: 'Buscar por título ou código',
    all: 'Todos os status',
    draft: 'Rascunho',
    published: 'Publicado',
    empty: 'Nenhum relatório encontrado.',
    loading: 'Carregando relatórios',
    code: 'Código',
    report: 'Relatório',
    author: 'Autor',
    occurrences: 'Ocorrências',
    updated: 'Atualizado',
    publication: 'Última publicação',
    actions: 'Ações',
    edit: 'Editar',
    previous: 'Anterior',
    next: 'Próxima',
    newTitle: 'Criar relatório',
    reportTitle: 'Título',
    description: 'Descrição',
    cancel: 'Cancelar',
    continue: 'Criar e continuar',
    back: 'Voltar à lista',
    save: 'Salvar rascunho',
    saving: 'Salvando…',
    sources: 'Fontes do rascunho',
    occurrenceSource: 'Ocorrências revisadas',
    reportSource: 'Relatórios publicados',
    findOccurrence: 'Buscar item ou descrição',
    findReport: 'Buscar relatório publicado',
    addSelected: 'Adicionar selecionados',
    selected: 'selecionados',
    direct: 'Diretas',
    inherited: 'Relatórios fonte',
    remove: 'Remover',
    preview: 'Prévia consolidada',
    refresh: 'Atualizar prévia',
    totalBrl: 'Valor BRL',
    totalUsd: 'Valor USD',
    publish: 'Publicar nova revisão',
    publishConfirm: 'Publicar uma versão imutável deste rascunho?',
    history: 'Histórico de versões',
    revision: 'Revisão',
    publishedAt: 'Publicada em',
    export: 'Exportar',
    preparing: 'Processando',
    download: 'Baixar',
    noSources: 'Adicione ocorrências revisadas ou relatórios publicados para formar a prévia.',
    conflict:
      'O rascunho foi alterado em outra sessão. Recarregamos a versão atual; revise antes de salvar novamente.',
    genericError: 'Não foi possível concluir a operação. Tente novamente.',
    close: 'Fechar',
    liveDraft: 'Prévia dinâmica',
    lineage: 'rotas de origem',
    archive: 'Arquivado',
    status: 'Status',
    requiredTitle: 'Informe um título.',
    savedAt: 'Salvo às',
    allSaved: 'Todas as alterações salvas',
    retrySave: 'Tentar salvar novamente',
    addOccurrences: 'Adicionar ocorrências',
    addReports: 'Vincular relatórios',
    noOccurrencesSelected: 'Nenhuma ocorrência direta vinculada a este rascunho.',
    noReportsSelected: 'Nenhum relatório publicado vinculado a este rascunho.',
    drawerOccurrencesTitle: 'Adicionar Ocorrências Revisadas',
    drawerReportsTitle: 'Vincular Relatórios Publicados',
    selectAll: 'Selecionar visíveis',
    clearSelection: 'Limpar seleção',
    added: 'Adicionado',
    filters: 'Filtros',
    filterTitle: 'Filtrar relatórios',
    clearFilters: 'Limpar filtros',
    applyFilters: 'Aplicar filtros',
  },
  en: {
    title: 'Scrap Reports',
    subtitle: 'Compose, publish, and export traceable analyses.',
    create: 'New report',
    search: 'Search by title or code',
    all: 'All statuses',
    draft: 'Draft',
    published: 'Published',
    empty: 'No reports found.',
    loading: 'Loading reports',
    code: 'Code',
    report: 'Report',
    author: 'Author',
    occurrences: 'Occurrences',
    updated: 'Updated',
    publication: 'Latest publication',
    actions: 'Actions',
    edit: 'Edit',
    previous: 'Previous',
    next: 'Next',
    newTitle: 'Create report',
    reportTitle: 'Title',
    description: 'Description',
    cancel: 'Cancel',
    continue: 'Create and continue',
    back: 'Back to list',
    save: 'Save draft',
    saving: 'Saving…',
    sources: 'Draft sources',
    occurrenceSource: 'Reviewed occurrences',
    reportSource: 'Published reports',
    findOccurrence: 'Search item or description',
    findReport: 'Search published report',
    addSelected: 'Add selected',
    selected: 'selected',
    direct: 'Direct',
    inherited: 'Source reports',
    remove: 'Remove',
    preview: 'Consolidated preview',
    refresh: 'Refresh preview',
    totalBrl: 'BRL amount',
    totalUsd: 'USD amount',
    publish: 'Publish new revision',
    publishConfirm: 'Publish an immutable version of this draft?',
    history: 'Version history',
    revision: 'Revision',
    publishedAt: 'Published at',
    export: 'Export',
    preparing: 'Processing',
    download: 'Download',
    noSources: 'Add reviewed occurrences or published reports to build the preview.',
    conflict:
      'This draft changed in another session. We reloaded the current version; review it before saving again.',
    genericError: 'The operation could not be completed. Try again.',
    close: 'Close',
    liveDraft: 'Live preview',
    lineage: 'source paths',
    archive: 'Archived',
    status: 'Status',
    requiredTitle: 'Enter a title.',
    savedAt: 'Saved at',
    allSaved: 'All changes saved',
    retrySave: 'Retry saving',
    addOccurrences: 'Add occurrences',
    addReports: 'Link reports',
    noOccurrencesSelected: 'No direct occurrences linked to this draft yet.',
    noReportsSelected: 'No published reports linked to this draft yet.',
    drawerOccurrencesTitle: 'Add Reviewed Occurrences',
    drawerReportsTitle: 'Link Published Reports',
    selectAll: 'Select visible',
    clearSelection: 'Clear selection',
    added: 'Added',
    filters: 'Filters',
    filterTitle: 'Filter reports',
    clearFilters: 'Clear filters',
    applyFilters: 'Apply filters',
  },
  ko: {
    title: '스크랩 보고서',
    subtitle: '추적 가능한 분석을 구성하고 게시 및 내보냅니다.',
    create: '새 보고서',
    search: '제목 또는 코드 검색',
    all: '모든 상태',
    draft: '초안',
    published: '게시됨',
    empty: '보고서가 없습니다.',
    loading: '보고서 로드 중',
    code: '코드',
    report: '보고서',
    author: '작성자',
    occurrences: '발생 건',
    updated: '업데이트',
    publication: '최근 게시',
    actions: '작업',
    edit: '편집',
    previous: '이전',
    next: '다음',
    newTitle: '보고서 만들기',
    reportTitle: '제목',
    description: '설명',
    cancel: '취소',
    continue: '만들고 계속',
    back: '목록으로',
    save: '초안 저장',
    saving: '저장 중…',
    sources: '초안 소스',
    occurrenceSource: '검토된 발생 건',
    reportSource: '게시된 보고서',
    findOccurrence: '품목 또는 설명 검색',
    findReport: '게시된 보고서 검색',
    addSelected: '선택 항목 추가',
    selected: '개 선택',
    direct: '직접',
    inherited: '소스 보고서',
    remove: '제거',
    preview: '통합 미리보기',
    refresh: '미리보기 새로고침',
    totalBrl: 'BRL 금액',
    totalUsd: 'USD 금액',
    publish: '새 개정 게시',
    publishConfirm: '이 초안의 변경 불가능한 버전을 게시하시겠습니까?',
    history: '버전 기록',
    revision: '개정',
    publishedAt: '게시일',
    export: '내보내기',
    preparing: '처리 중',
    download: '다운로드',
    noSources: '미리보기를 만들려면 검토된 발생 건 또는 게시된 보고서를 추가하세요.',
    conflict: '다른 세션에서 초안이 변경되었습니다. 현재 버전을 다시 불러왔습니다.',
    genericError: '작업을 완료할 수 없습니다. 다시 시도하세요.',
    close: '닫기',
    liveDraft: '동적 미리보기',
    lineage: '소스 경로',
    archive: '보관됨',
    status: '상태',
    requiredTitle: '제목을 입력하세요.',
    savedAt: '저장됨: ',
    allSaved: '모든 변경사항 저장됨',
    retrySave: '다시 저장',
    addOccurrences: '발생 내역 추가',
    addReports: '보고서 연결',
    noOccurrencesSelected: '이 초안에 연결된 직접 발생 내역이 없습니다.',
    noReportsSelected: '이 초안에 연결된 게시된 보고서가 없습니다.',
    drawerOccurrencesTitle: '검토된 발생 내역 추가',
    drawerReportsTitle: '게시된 보고서 연결',
    selectAll: '표시된 항목 선택',
    clearSelection: '선택 해제',
    added: '추가됨',
    filters: '필터',
    filterTitle: '보고서 필터',
    clearFilters: '필터 지우기',
    applyFilters: '필터 적용',
  },
} as const;
