export const workflowCopy = {
  pt: {
    plans: 'Planos de ação',
    filterPlans: 'Filtrar planos',
    searchPlans: 'Buscar plano...',
    openPlans: 'Em aberto',
    completedPlans: 'Concluídos',
    sort: 'Ordenar por',
    newest: 'Mais recentes',
    oldest: 'Mais antigos',
    titleSort: 'Título',
    noPlansMatch: 'Nenhum plano corresponde aos filtros selecionados.',
    alerts: 'Alertas',
    newPlan: 'Novo plano',
    newTask: 'Nova tarefa',
    title: 'Título',
    description: 'Descrição',
    save: 'Salvar',
    close: 'Fechar',
    back: 'Voltar',
    loading: 'Carregando…',
    empty: 'Nenhum registro encontrado.',
    previous: 'Anterior',
    next: 'Próxima',
    participants: 'Participantes',
    profiles: 'Perfis',
    due: 'Prazo',
    priority: 'Prioridade',
    blocked: 'Motivo do bloqueio',
    blockedState: 'Bloqueada',
    blockReasonOptional: 'Motivo (opcional)',
    history: 'Histórico',
    comment: 'Comentário',
    validate: 'Validar conclusão',
    reopen: 'Reabrir',
    move: 'Mover para',
    planned: 'Planejada',
    progress: 'Em andamento',
    verification: 'Em validação',
    completed: 'Concluída',
    reports: 'Relatórios publicados',
    selectReport: 'Selecione ao menos um relatório publicado.',
    occurrences: 'Ocorrências relacionadas',
    searchOccurrences: 'Buscar por item ou descrição',
    noOccurrences: 'Nenhuma ocorrência revisada encontrada.',
    selectedOccurrences: 'Vinculadas',
    activity: 'Atividade',
    addComment: 'Adicionar comentário',
    noActivity: 'Ainda não há atividade.',
    taskUpdated: 'Tarefa atualizada',
    tags: 'Tags',
    addTag: 'Adicionar tag',
    evidence: 'Evidências',
    attachEvidence: 'Anexar evidência',
    downloadEvidence: 'Baixar evidência',
    removeEvidence: 'Remover evidência',
    noEvidence: 'Nenhuma evidência anexada.',
    evidenceAdded: 'Evidência anexada',
    evidenceRemoved: 'Evidência removida',
    addReport: 'Vincular versão',
    finishPlan: 'Concluir plano',
    search: 'Buscar',
    read: 'Marcar como lido',
    unread: 'Não lidos',
    all: 'Todos',
    settings: 'Configurar alertas',
    type: 'Tipo',
    severity: 'Severidade',
    threshold: 'Limiar',
    currency: 'Moeda',
    window: 'Janela (dias)',
    cooldown: 'Intervalo mínimo (minutos)',
    dimension: 'Dimensão',
    enabled: 'Habilitada',
    email: 'Email simulado',
    front: 'No sistema',
    simulation: 'Emails simulados — nenhum email real foi enviado.',
    unavailable: 'Notificações e exportações indisponíveis: worker desabilitado.',
    error: 'Não foi possível concluir. Tente novamente.',
    conflict:
      'O registro mudou em outra sessão. Sua edição foi preservada; recarregue antes de tentar novamente.',
    dateFrom: 'Início do período',
    dateTo: 'Fim do período',
    details: 'Detalhes',
    open: 'Abrir registro',
    ruleName: 'Nome da regra',
    createRule: 'Nova regra',
    low: 'Baixa',
    medium: 'Média',
    high: 'Alta',
    urgent: 'Urgente',
    overdue: 'Atrasada',
    task: 'Tarefa',
    organization: 'Organização',
    item: 'Item',
    line: 'Linha',
    product: 'Produto',
    occurrence: 'Ocorrência',
    filter: 'Filtro (opcional)',
    reload: 'Recarregar',
    notificationsHistory: 'Histórico de notificações',
    filterAlerts: 'Filtrar notificações',
    clearFilters: 'Limpar filtros',
    applyFilters: 'Aplicar filtros',
    noAlertsMatch: 'Nenhum alerta registrado correspondente aos filtros selecionados.',
    date: 'Data',
    status: 'Status',
    actions: 'Ações',
    readStatus: 'Lido',
    unreadStatus: 'Não lido',
    page: 'Página',
    of: 'de',
    perPage: 'Por página',
    total: 'Total',
    filters: 'Filtros',
    observed: 'Observado',
    triggerSettings: 'Configuração de gatilhos',
    noRules: 'Nenhuma regra configurada',
    noRulesDescription: 'Crie regras automáticas para ser notificado sobre anomalias.',
    edit: 'Editar',
    notificationRule: 'Regra de notificação',
    editRule: 'Editar regra',
    notificationChannels: 'Canais de notificação',
    emailChannel: 'E-mail',
    outbox: 'Caixa de saída',
    noEmails: 'Nenhum e-mail registrado',
    noEmailsDescription: 'Nenhum e-mail de alerta foi disparado nesta sessão.',
    severityInfo: 'Informativo',
    severityWarning: 'Alerta',
    severityCritical: 'Crítico',
    severityPositive: 'Positivo',
    alertTypeScrapRelevant: 'Ocorrência relevante',
    alertTypeCostExceeded: 'Custo acima do limite',
    alertTypeGoalAchieved: 'Meta atingida',
    alertTypeIngestionFailed: 'Falha na importação',
    alertTypeUpdateLate: 'Atualização atrasada',
    alertTypeReportExportFailed: 'Falha na exportação',
    alertTypeTaskAssigned: 'Tarefa atribuída',
    alertTypeTaskDue: 'Prazo de tarefa',
    alertTypeTaskOverdue: 'Tarefa atrasada',
    alertTypeTaskBlocked: 'Tarefa bloqueada',
    alertTypeTaskVerification: 'Tarefa em validação',
    alertTypeTaskValidated: 'Tarefa validada',
    alertTypeReportExportCompleted: 'Exportação concluída',
    demoAlertTaskOverdueTitle: 'Prazo de ação corretiva próximo',
    demoAlertTaskOverdueDescription: 'Uma ação demonstrativa precisa de acompanhamento imediato.',
    demoAlertCostExceededTitle: 'Custo de Scrap acima do limite',
    demoAlertCostExceededDescription:
      'O custo acumulado do período demonstrativo ultrapassou o limite definido.',
    demoAlertTaskAssignedTitle: 'Nova tarefa atribuída para validação',
    demoAlertTaskAssignedDescription:
      'Uma tarefa de melhoria foi atribuída ao fluxo de demonstração.',
    demoAlertExportCompletedTitle: 'Relatório demonstrativo disponível',
    demoAlertExportCompletedDescription:
      'O relatório de acompanhamento foi preparado para consulta.',
    demoAlertScrapRelevantTitle: 'Ocorrência relevante identificada',
    demoAlertScrapRelevantDescription:
      'Uma ocorrência de Scrap requer análise de causa e plano de ação.',
  },
  en: {
    plans: 'Action plans',
    filterPlans: 'Filter plans',
    searchPlans: 'Search plans...',
    openPlans: 'Open',
    completedPlans: 'Completed',
    sort: 'Sort by',
    newest: 'Newest',
    oldest: 'Oldest',
    titleSort: 'Title',
    noPlansMatch: 'No plans match the selected filters.',
    alerts: 'Alerts',
    newPlan: 'New plan',
    newTask: 'New task',
    title: 'Title',
    description: 'Description',
    save: 'Save',
    close: 'Close',
    back: 'Back',
    loading: 'Loading…',
    empty: 'No records found.',
    previous: 'Previous',
    next: 'Next',
    participants: 'Participants',
    profiles: 'Profiles',
    due: 'Due date',
    priority: 'Priority',
    blocked: 'Blocking reason',
    blockedState: 'Blocked',
    blockReasonOptional: 'Reason (optional)',
    history: 'History',
    comment: 'Comment',
    validate: 'Validate completion',
    reopen: 'Reopen',
    move: 'Move to',
    planned: 'Planned',
    progress: 'In progress',
    verification: 'Under verification',
    completed: 'Completed',
    reports: 'Published reports',
    selectReport: 'Select at least one published report.',
    occurrences: 'Related occurrences',
    searchOccurrences: 'Search by item or description',
    noOccurrences: 'No reviewed occurrences found.',
    selectedOccurrences: 'Linked',
    activity: 'Activity',
    addComment: 'Add comment',
    noActivity: 'No activity yet.',
    taskUpdated: 'Task updated',
    tags: 'Tags',
    addTag: 'Add tag',
    evidence: 'Evidence',
    attachEvidence: 'Attach evidence',
    downloadEvidence: 'Download evidence',
    removeEvidence: 'Remove evidence',
    noEvidence: 'No evidence attached.',
    evidenceAdded: 'Evidence attached',
    evidenceRemoved: 'Evidence removed',
    addReport: 'Link version',
    finishPlan: 'Complete plan',
    search: 'Search',
    read: 'Mark as read',
    unread: 'Unread',
    all: 'All',
    settings: 'Alert settings',
    type: 'Type',
    severity: 'Severity',
    threshold: 'Threshold',
    currency: 'Currency',
    window: 'Window (days)',
    cooldown: 'Minimum interval (minutes)',
    dimension: 'Dimension',
    enabled: 'Enabled',
    email: 'Simulated email',
    front: 'In app',
    simulation: 'Simulated emails — no real email was sent.',
    unavailable: 'Notifications and exports unavailable: worker disabled.',
    error: 'Unable to complete. Try again.',
    conflict:
      'This record changed in another session. Your edits were preserved; reload before retrying.',
    dateFrom: 'Period start',
    dateTo: 'Period end',
    details: 'Details',
    open: 'Open record',
    ruleName: 'Rule name',
    createRule: 'New rule',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    urgent: 'Urgent',
    overdue: 'Overdue',
    task: 'Task',
    organization: 'Organization',
    item: 'Item',
    line: 'Line',
    product: 'Product',
    occurrence: 'Occurrence',
    filter: 'Filter (optional)',
    reload: 'Reload',
    notificationsHistory: 'Notification history',
    filterAlerts: 'Filter notifications',
    clearFilters: 'Clear filters',
    applyFilters: 'Apply filters',
    noAlertsMatch: 'No alerts match the selected filters.',
    date: 'Date',
    status: 'Status',
    actions: 'Actions',
    readStatus: 'Read',
    unreadStatus: 'Unread',
    page: 'Page',
    of: 'of',
    perPage: 'Per page',
    total: 'Total',
    filters: 'Filters',
    observed: 'Observed',
    triggerSettings: 'Trigger settings',
    noRules: 'No rules configured',
    noRulesDescription: 'Create automatic rules to be notified about anomalies.',
    edit: 'Edit',
    notificationRule: 'Notification rule',
    editRule: 'Edit rule',
    notificationChannels: 'Notification channels',
    emailChannel: 'Email',
    outbox: 'Outbox',
    noEmails: 'No emails recorded',
    noEmailsDescription: 'No alert email was sent in this session.',
    severityInfo: 'Info',
    severityWarning: 'Warning',
    severityCritical: 'Critical',
    severityPositive: 'Positive',
    alertTypeScrapRelevant: 'Relevant occurrence',
    alertTypeCostExceeded: 'Cost threshold exceeded',
    alertTypeGoalAchieved: 'Goal achieved',
    alertTypeIngestionFailed: 'Import failed',
    alertTypeUpdateLate: 'Update delayed',
    alertTypeReportExportFailed: 'Export failed',
    alertTypeTaskAssigned: 'Task assigned',
    alertTypeTaskDue: 'Task due date',
    alertTypeTaskOverdue: 'Overdue task',
    alertTypeTaskBlocked: 'Blocked task',
    alertTypeTaskVerification: 'Task under verification',
    alertTypeTaskValidated: 'Task validated',
    alertTypeReportExportCompleted: 'Export completed',
    demoAlertTaskOverdueTitle: 'Corrective action deadline approaching',
    demoAlertTaskOverdueDescription: 'A demo action needs immediate follow-up.',
    demoAlertCostExceededTitle: 'Scrap cost above the threshold',
    demoAlertCostExceededDescription:
      'The accumulated cost for the demo period exceeded the defined limit.',
    demoAlertTaskAssignedTitle: 'New task assigned for validation',
    demoAlertTaskAssignedDescription: 'An improvement task was assigned to the demo workflow.',
    demoAlertExportCompletedTitle: 'Demo report available',
    demoAlertExportCompletedDescription: 'The monitoring report has been prepared for viewing.',
    demoAlertScrapRelevantTitle: 'Relevant occurrence identified',
    demoAlertScrapRelevantDescription:
      'A Scrap occurrence requires cause analysis and an action plan.',
  },
  ko: {
    plans: '실행 계획',
    filterPlans: '계획 필터',
    searchPlans: '계획 검색...',
    openPlans: '진행 중',
    completedPlans: '완료',
    sort: '정렬 기준',
    newest: '최신순',
    oldest: '오래된순',
    titleSort: '제목순',
    noPlansMatch: '선택한 필터와 일치하는 계획이 없습니다.',
    alerts: '알림',
    newPlan: '새 계획',
    newTask: '새 작업',
    title: '제목',
    description: '설명',
    save: '저장',
    close: '닫기',
    back: '뒤로',
    loading: '로드 중…',
    empty: '기록이 없습니다.',
    previous: '이전',
    next: '다음',
    participants: '참여자',
    profiles: '프로필',
    due: '기한',
    priority: '우선순위',
    blocked: '차단 사유',
    blockedState: '차단됨',
    blockReasonOptional: '사유 (선택)',
    history: '변경 기록',
    comment: '댓글',
    validate: '완료 검증',
    reopen: '다시 열기',
    move: '이동',
    planned: '계획됨',
    progress: '진행 중',
    verification: '검증 중',
    completed: '완료됨',
    reports: '게시된 보고서',
    selectReport: '게시된 보고서를 하나 이상 선택하세요.',
    occurrences: '관련 발생 건',
    searchOccurrences: '품목 또는 설명으로 검색',
    noOccurrences: '검토된 발생 건이 없습니다.',
    selectedOccurrences: '연결됨',
    activity: '활동',
    addComment: '댓글 추가',
    noActivity: '아직 활동이 없습니다.',
    taskUpdated: '작업 업데이트',
    tags: '태그',
    addTag: '태그 추가',
    evidence: '증빙 자료',
    attachEvidence: '증빙 첨부',
    downloadEvidence: '증빙 다운로드',
    removeEvidence: '증빙 제거',
    noEvidence: '첨부된 증빙이 없습니다.',
    evidenceAdded: '증빙 첨부됨',
    evidenceRemoved: '증빙 제거됨',
    addReport: '버전 연결',
    finishPlan: '계획 완료',
    search: '검색',
    read: '읽음으로 표시',
    unread: '읽지 않음',
    all: '전체',
    settings: '알림 설정',
    type: '유형',
    severity: '심각도',
    threshold: '임계값',
    currency: '통화',
    window: '기간 (일)',
    cooldown: '최소 간격 (분)',
    dimension: '차원',
    enabled: '활성화',
    email: '이메일 시뮬레이션',
    front: '앱 내',
    simulation: '이메일 시뮬레이션 — 실제 이메일은 발송되지 않았습니다.',
    unavailable: '작업자가 비활성화되어 알림과 내보내기를 사용할 수 없습니다.',
    error: '완료할 수 없습니다. 다시 시도하세요.',
    conflict: '다른 세션에서 변경되었습니다. 편집 내용은 보존되었습니다. 다시 로드하세요.',
    dateFrom: '기간 시작',
    dateTo: '기간 종료',
    details: '상세',
    open: '기록 열기',
    ruleName: '규칙 이름',
    createRule: '새 규칙',
    low: '낮음',
    medium: '보통',
    high: '높음',
    urgent: '긴급',
    overdue: '기한 초과',
    task: '작업',
    organization: '조직',
    item: '품목',
    line: '라인',
    product: '제품',
    occurrence: '발생',
    filter: '필터 (선택)',
    reload: '다시 로드',
    notificationsHistory: '알림 기록',
    filterAlerts: '알림 필터',
    clearFilters: '필터 지우기',
    applyFilters: '필터 적용',
    noAlertsMatch: '선택한 필터와 일치하는 알림이 없습니다.',
    date: '날짜',
    status: '상태',
    actions: '작업',
    readStatus: '읽음',
    unreadStatus: '읽지 않음',
    page: '페이지',
    of: '/',
    perPage: '페이지당',
    total: '합계',
    filters: '필터',
    observed: '관측값',
    triggerSettings: '트리거 설정',
    noRules: '설정된 규칙이 없습니다',
    noRulesDescription: '이상 징후 알림을 받을 자동 규칙을 만드세요.',
    edit: '수정',
    notificationRule: '알림 규칙',
    editRule: '규칙 수정',
    notificationChannels: '알림 채널',
    emailChannel: '이메일',
    outbox: '보낸편지함',
    noEmails: '기록된 이메일이 없습니다',
    noEmailsDescription: '이 세션에서 전송된 알림 이메일이 없습니다.',
    severityInfo: '정보',
    severityWarning: '경고',
    severityCritical: '위험',
    severityPositive: '긍정',
    alertTypeScrapRelevant: '중요 발생 건',
    alertTypeCostExceeded: '비용 한도 초과',
    alertTypeGoalAchieved: '목표 달성',
    alertTypeIngestionFailed: '가져오기 실패',
    alertTypeUpdateLate: '업데이트 지연',
    alertTypeReportExportFailed: '내보내기 실패',
    alertTypeTaskAssigned: '작업 할당됨',
    alertTypeTaskDue: '작업 기한',
    alertTypeTaskOverdue: '작업 기한 초과',
    alertTypeTaskBlocked: '차단된 작업',
    alertTypeTaskVerification: '작업 검증 중',
    alertTypeTaskValidated: '작업 검증 완료',
    alertTypeReportExportCompleted: '내보내기 완료',
    demoAlertTaskOverdueTitle: '시정 조치 기한이 임박했습니다',
    demoAlertTaskOverdueDescription: '데모 조치에 즉시 후속 조치가 필요합니다.',
    demoAlertCostExceededTitle: '스크랩 비용이 한도를 초과했습니다',
    demoAlertCostExceededDescription: '데모 기간의 누적 비용이 설정된 한도를 초과했습니다.',
    demoAlertTaskAssignedTitle: '검증을 위한 새 작업이 할당되었습니다',
    demoAlertTaskAssignedDescription: '개선 작업이 데모 워크플로에 할당되었습니다.',
    demoAlertExportCompletedTitle: '데모 보고서를 사용할 수 있습니다',
    demoAlertExportCompletedDescription: '모니터링 보고서를 조회할 수 있도록 준비했습니다.',
    demoAlertScrapRelevantTitle: '중요 발생 건이 식별되었습니다',
    demoAlertScrapRelevantDescription: '스크랩 발생 건에는 원인 분석과 조치 계획이 필요합니다.',
  },
} as const;
