export const workflowCopy = {
  pt: {
    plans: 'Planos de ação',
    alerts: 'Alertas',
    newPlan: 'Novo plano',
    newTask: 'Nova tarefa',
    title: 'Título',
    description: 'Descrição',
    save: 'Salvar',
    close: 'Fechar',
    back: 'Voltar',
    loading: 'Carregando…',
    empty: 'Nenhum registro encontrado.',
    previous: 'Anterior',
    next: 'Próxima',
    participants: 'Participantes',
    profiles: 'Perfis',
    due: 'Prazo',
    priority: 'Prioridade',
    blocked: 'Motivo do bloqueio',
    history: 'Histórico',
    comment: 'Comentário',
    validate: 'Validar conclusão',
    reopen: 'Reabrir',
    move: 'Mover para',
    planned: 'Planejada',
    progress: 'Em andamento',
    verification: 'Em validação',
    completed: 'Concluída',
    reports: 'Relatórios publicados',
    addReport: 'Vincular versão',
    finishPlan: 'Concluir plano',
    search: 'Buscar',
    read: 'Marcar como lido',
    unread: 'Não lidos',
    all: 'Todos',
    settings: 'Configurar alertas',
    type: 'Tipo',
    severity: 'Severidade',
    threshold: 'Limiar',
    currency: 'Moeda',
    window: 'Janela (dias)',
    cooldown: 'Intervalo mínimo (minutos)',
    dimension: 'Dimensão',
    enabled: 'Habilitada',
    email: 'Email simulado',
    front: 'No sistema',
    simulation: 'Emails simulados — nenhum email real foi enviado.',
    unavailable: 'Notificações e exportações indisponíveis: worker desabilitado.',
    error: 'Não foi possível concluir. Tente novamente.',
    conflict:
      'O registro mudou em outra sessão. Sua edição foi preservada; recarregue antes de tentar novamente.',
    dateFrom: 'Início do período',
    dateTo: 'Fim do período',
    details: 'Detalhes',
    open: 'Abrir registro',
    ruleName: 'Nome da regra',
    createRule: 'Nova regra',
    low: 'Baixa',
    medium: 'Média',
    high: 'Alta',
    urgent: 'Urgente',
    overdue: 'Atrasada',
    task: 'Tarefa',
    organization: 'Organização',
    item: 'Item',
    line: 'Linha',
    product: 'Produto',
    occurrence: 'Ocorrência',
    filter: 'Filtro (opcional)',
    reload: 'Recarregar',
  },
  en: {
    plans: 'Action plans',
    alerts: 'Alerts',
    newPlan: 'New plan',
    newTask: 'New task',
    title: 'Title',
    description: 'Description',
    save: 'Save',
    close: 'Close',
    back: 'Back',
    loading: 'Loading…',
    empty: 'No records found.',
    previous: 'Previous',
    next: 'Next',
    participants: 'Participants',
    profiles: 'Profiles',
    due: 'Due date',
    priority: 'Priority',
    blocked: 'Blocking reason',
    history: 'History',
    comment: 'Comment',
    validate: 'Validate completion',
    reopen: 'Reopen',
    move: 'Move to',
    planned: 'Planned',
    progress: 'In progress',
    verification: 'Under verification',
    completed: 'Completed',
    reports: 'Published reports',
    addReport: 'Link version',
    finishPlan: 'Complete plan',
    search: 'Search',
    read: 'Mark as read',
    unread: 'Unread',
    all: 'All',
    settings: 'Alert settings',
    type: 'Type',
    severity: 'Severity',
    threshold: 'Threshold',
    currency: 'Currency',
    window: 'Window (days)',
    cooldown: 'Minimum interval (minutes)',
    dimension: 'Dimension',
    enabled: 'Enabled',
    email: 'Simulated email',
    front: 'In app',
    simulation: 'Simulated emails — no real email was sent.',
    unavailable: 'Notifications and exports unavailable: worker disabled.',
    error: 'Unable to complete. Try again.',
    conflict:
      'This record changed in another session. Your edits were preserved; reload before retrying.',
    dateFrom: 'Period start',
    dateTo: 'Period end',
    details: 'Details',
    open: 'Open record',
    ruleName: 'Rule name',
    createRule: 'New rule',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    urgent: 'Urgent',
    overdue: 'Overdue',
    task: 'Task',
    organization: 'Organization',
    item: 'Item',
    line: 'Line',
    product: 'Product',
    occurrence: 'Occurrence',
    filter: 'Filter (optional)',
    reload: 'Reload',
  },
  ko: {
    plans: '실행 계획',
    alerts: '알림',
    newPlan: '새 계획',
    newTask: '새 작업',
    title: '제목',
    description: '설명',
    save: '저장',
    close: '닫기',
    back: '뒤로',
    loading: '로드 중…',
    empty: '기록이 없습니다.',
    previous: '이전',
    next: '다음',
    participants: '참여자',
    profiles: '프로필',
    due: '기한',
    priority: '우선순위',
    blocked: '차단 사유',
    history: '변경 기록',
    comment: '댓글',
    validate: '완료 검증',
    reopen: '다시 열기',
    move: '이동',
    planned: '계획됨',
    progress: '진행 중',
    verification: '검증 중',
    completed: '완료됨',
    reports: '게시된 보고서',
    addReport: '버전 연결',
    finishPlan: '계획 완료',
    search: '검색',
    read: '읽음으로 표시',
    unread: '읽지 않음',
    all: '전체',
    settings: '알림 설정',
    type: '유형',
    severity: '심각도',
    threshold: '임계값',
    currency: '통화',
    window: '기간 (일)',
    cooldown: '최소 간격 (분)',
    dimension: '차원',
    enabled: '활성화',
    email: '이메일 시뮬레이션',
    front: '앱 내',
    simulation: '이메일 시뮬레이션 — 실제 이메일은 발송되지 않았습니다.',
    unavailable: '작업자가 비활성화되어 알림과 내보내기를 사용할 수 없습니다.',
    error: '완료할 수 없습니다. 다시 시도하세요.',
    conflict: '다른 세션에서 변경되었습니다. 편집 내용은 보존되었습니다. 다시 로드하세요.',
    dateFrom: '기간 시작',
    dateTo: '기간 종료',
    details: '상세',
    open: '기록 열기',
    ruleName: '규칙 이름',
    createRule: '새 규칙',
    low: '낮음',
    medium: '보통',
    high: '높음',
    urgent: '긴급',
    overdue: '기한 초과',
    task: '작업',
    organization: '조직',
    item: '품목',
    line: '라인',
    product: '제품',
    occurrence: '발생',
    filter: '필터 (선택)',
    reload: '다시 로드',
  },
} as const;
