"""Governance workflows and recoverable exports; preserve historical rows."""

import uuid
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "20260909_14"
down_revision = "20260909_13"
branch_labels = None
depends_on = None


def _create_tables():
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table(
        "gov_published_evidence",
        sa.Column("source_attachment_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    _create_table(
        "gov_action_plans",
        sa.Column("factory_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('OPEN','COMPLETED')", name="ck_gov_plan_status"),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["factory_id"], ["gov_factories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    _create_table(
        "gov_plan_reports",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("report_version_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["gov_action_plans.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["report_version_id"], ["gov_report_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "report_version_id", name="uq_gov_plan_report"),
    )
    _create_table(
        "gov_action_participants",
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["action_id"], ["gov_actions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id", "user_id", name="uq_gov_action_participant"),
    )
    _create_table(
        "gov_action_occurrences",
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("occurrence_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["action_id"], ["gov_actions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["occurrence_id"], ["scrap_occurrences.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id", "occurrence_id", name="uq_gov_action_occurrence"),
    )
    _create_table(
        "gov_notification_rules",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    _create_table(
        "gov_rule_evaluations",
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("window_key", sa.String(length=80), nullable=False),
        sa.Column("subject", sa.String(length=240), nullable=False),
        sa.Column("observed", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("last_fired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["rule_id"], ["gov_notification_rules.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "window_key", "subject", name="uq_gov_rule_window"),
    )
    _create_table(
        "gov_alerts",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("body", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["gov_outbox_events.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    _create_table(
        "gov_alert_recipients",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["gov_alerts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alert_id", "user_id", name="uq_gov_alert_recipient"),
    )
    _create_table(
        "gov_email_deliveries",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recipient", sa.String(length=100), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["gov_outbox_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", name="uq_gov_email_recipient"),
    )
    _create_table(
        "gov_event_attempts",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("error", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["gov_outbox_events.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def _create_table(name, *args, **kwargs):
    if name not in sa.inspect(op.get_bind()).get_table_names():
        op.create_table(name, *args, **kwargs)


def upgrade():
    _create_tables()
    inspector = sa.inspect(op.get_bind())
    export_checks = {c["name"]: c["sqltext"] for c in inspector.get_check_constraints("gov_export_jobs")}
    action_checks = {c["name"]: c["sqltext"] for c in inspector.get_check_constraints("gov_actions")}
    migrate_states = "COMPLETED" not in action_checks.get("ck_gov_action_status", "")
    columns = {c["name"] for c in sa.inspect(op.get_bind()).get_columns("gov_export_jobs")}
    with op.batch_alter_table("gov_export_jobs") as batch:
        if "lease_token" not in columns:
            batch.add_column(sa.Column("lease_token", sa.Uuid(), nullable=True))
        if "lease_until" not in columns:
            batch.add_column(sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True))
        if "MARKDOWN" not in export_checks.get("ck_gov_export_format", ""):
            batch.drop_constraint("ck_gov_export_format", type_="check")
            batch.create_check_constraint("ck_gov_export_format", "format IN ('PDF','PPTX','CSV','MARKDOWN','XLSX')")
    columns = {c["name"] for c in sa.inspect(op.get_bind()).get_columns("gov_actions")}
    with op.batch_alter_table("gov_actions") as batch:
        for column in [
            sa.Column("plan_id", sa.Uuid(), nullable=True),
            sa.Column("description", sa.Text(), nullable=False, server_default=""),
            sa.Column("priority", sa.String(10), nullable=False, server_default="MEDIUM"),
            sa.Column("position", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("author_id", sa.Integer(), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
            sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("validated_by_id", sa.Integer(), nullable=True),
        ]:
            if column.name not in columns:
                batch.add_column(column)
        if "plan_id" not in columns:
            batch.create_foreign_key("fk_action_plan", "gov_action_plans", ["plan_id"], ["id"], ondelete="RESTRICT")
            batch.create_foreign_key("fk_action_author", "user", ["author_id"], ["id"], ondelete="RESTRICT")
            batch.create_foreign_key("fk_action_validator", "user", ["validated_by_id"], ["id"], ondelete="RESTRICT")
        if migrate_states:
            batch.drop_constraint("ck_gov_action_status", type_="check")
    # Preserve legacy state explicitly in immutable audit history before mapping.
    connection = op.get_bind()

    rows = (
        connection.execute(sa.text("SELECT id, status, factory_id, title, owner_id FROM gov_actions WHERE plan_id IS NULL"))
        .mappings()
        .all()
    )
    plan_table = sa.table(
        "gov_action_plans",
        sa.column("id", sa.Uuid()),
        sa.column("factory_id", sa.Uuid()),
        sa.column("title"),
        sa.column("description"),
        sa.column("status"),
        sa.column("author_id"),
        sa.column("version"),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    audit_table = sa.table(
        "gov_audit_events",
        sa.column("id", sa.Uuid()),
        sa.column("entity_id", sa.Uuid()),
        sa.column("event_type"),
        sa.column("entity_type"),
        sa.column("payload", sa.JSON()),
        sa.column("correlation_id"),
        sa.column("actor_id"),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    action_table = sa.table("gov_actions", sa.column("id", sa.Uuid()), sa.column("plan_id", sa.Uuid()), sa.column("status"))
    participant_table = sa.table(
        "gov_action_participants",
        sa.column("id", sa.Uuid()),
        sa.column("action_id", sa.Uuid()),
        sa.column("user_id"),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    for row in rows:
        action_id, factory_id, plan_id = uuid.UUID(str(row["id"])), uuid.UUID(str(row["factory_id"])), uuid.uuid4()
        timestamp = datetime.now(UTC)
        connection.execute(
            plan_table.insert().values(
                id=plan_id,
                factory_id=factory_id,
                title=row["title"],
                description="Migrated legacy action",
                status="OPEN",
                author_id=row["owner_id"],
                version=1,
                created_at=timestamp,
            )
        )
        connection.execute(
            audit_table.insert().values(
                id=uuid.uuid4(),
                entity_id=action_id,
                event_type="LEGACY_ACTION_MIGRATED",
                entity_type="ACTION",
                payload={"previous_status": row["status"]},
                correlation_id=str(action_id),
                created_at=timestamp,
            )
        )
        # EFFECTIVE is not silently treated as the MVP explicit human validation.
        status = {"IMPLEMENTED": "UNDER_VERIFICATION", "EFFECTIVE": "UNDER_VERIFICATION", "CANCELLED": "PLANNED"}.get(
            row["status"], row["status"]
        )
        connection.execute(action_table.update().where(action_table.c.id == action_id).values(plan_id=plan_id, status=status))
        if row["owner_id"]:
            connection.execute(
                participant_table.insert().values(
                    id=uuid.uuid4(), action_id=action_id, user_id=row["owner_id"], created_at=timestamp
                )
            )
    if migrate_states:
        with op.batch_alter_table("gov_actions") as batch:
            batch.create_check_constraint(
                "ck_gov_action_status", "status IN ('PLANNED','IN_PROGRESS','UNDER_VERIFICATION','COMPLETED')"
            )
    indexes = {
        "gov_actions": [("ix_gov_plan_board", ["plan_id", "status", "position", "id"])],
        "gov_alert_recipients": [("ix_gov_alert_recipient_user", ["user_id", "read_at", "alert_id"])],
        "gov_email_deliveries": [("ix_gov_email_user", ["user_id", "created_at", "id"])],
        "gov_rule_evaluations": [("ix_gov_rule_evaluation", ["rule_id", "window_key"])],
    }
    for table, definitions in indexes.items():
        existing = {i["name"] for i in sa.inspect(connection).get_indexes(table)}
        for name, fields in definitions:
            if name not in existing:
                op.create_index(name, table, fields)


def downgrade():
    raise RuntimeError("This data-preserving workflow migration requires an explicit restoration plan to downgrade")
