"""Add production and quality governance persistence.

Frozen schema: do not import runtime models into this migration.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = "20260906_12"
down_revision = "20260904_11"
branch_labels = None
depends_on = None


def _create_tables() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gov_factories",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("timezone", sa.String(length=60), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "gov_outbox_events",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("attempts >= 0", name="ck_gov_outbox_attempts"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_gov_outbox_pending",
        "gov_outbox_events",
        ["available_at", "id"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
        sqlite_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "gov_audit_cycles",
        sa.Column("factory_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("population", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("conclusion", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('PLANNED','OPEN','FIELDWORK','IN_REVIEW','CLOSED','CANCELLED')", name="ck_gov_audit_status"
        ),
        sa.CheckConstraint("date_to >= date_from", name="ck_gov_audit_dates"),
        sa.ForeignKeyConstraint(["factory_id"], ["gov_factories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("factory_id", "code", name="uq_gov_audit_code"),
    )
    op.create_table(
        "gov_consumer_receipts",
        sa.Column("consumer", sa.String(length=100), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["gov_outbox_events.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("consumer", "event_id", name="uq_gov_consumer_event"),
    )
    op.create_table(
        "gov_dataset_snapshots",
        sa.Column("scope", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("metrics", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("factory_id", sa.Uuid(), nullable=False),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["factory_id"], ["gov_factories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gov_dataset_snapshots_factory_id"), "gov_dataset_snapshots", ["factory_id"], unique=False)
    op.create_table(
        "gov_production_lines",
        sa.Column("factory_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["factory_id"], ["gov_factories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("factory_id", "code", name="uq_gov_line_code"),
    )
    op.create_table(
        "gov_reports",
        sa.Column("factory_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["factory_id"], ["gov_factories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("factory_id", "code", name="uq_gov_report_code"),
    )
    op.create_table(
        "gov_review_policies",
        sa.Column("factory_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("rules", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("revision > 0", name="ck_gov_policy_revision"),
        sa.ForeignKeyConstraint(["factory_id"], ["gov_factories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("factory_id", "code", "revision", name="uq_gov_policy_revision"),
    )
    op.create_table(
        "gov_actions",
        sa.Column("factory_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('PLANNED','IN_PROGRESS','IMPLEMENTED','UNDER_VERIFICATION','EFFECTIVE','CANCELLED')",
            name="ck_gov_action_status",
        ),
        sa.ForeignKeyConstraint(["factory_id"], ["gov_factories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("factory_id", "code", name="uq_gov_action_code"),
    )
    op.create_index("ix_gov_action_board", "gov_actions", ["factory_id", "status", "due_at", "id"], unique=False)
    op.create_index("ix_gov_action_owner", "gov_actions", ["owner_id", "status", "due_at"], unique=False)
    op.create_table(
        "gov_audit_events",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("correlation_id", sa.String(length=160), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gov_audit_events_correlation_id"), "gov_audit_events", ["correlation_id"], unique=False)
    op.create_index("ix_gov_event_entity", "gov_audit_events", ["entity_type", "entity_id", "created_at"], unique=False)
    op.create_table(
        "gov_cases",
        sa.Column("factory_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('NEW','TRIAGED','INVESTIGATING','AWAITING_APPROVAL','ANALYZED','CLOSED')", name="ck_gov_case_status"
        ),
        sa.ForeignKeyConstraint(["factory_id"], ["gov_factories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("factory_id", "code", name="uq_gov_case_code"),
    )
    op.create_index("ix_gov_case_queue", "gov_cases", ["factory_id", "status", "due_at", "id"], unique=False)
    op.create_table(
        "gov_line_layouts",
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("revision > 0", name="ck_gov_layout_revision"),
        sa.CheckConstraint("valid_to IS NULL OR valid_to > valid_from", name="ck_gov_layout_dates"),
        sa.ForeignKeyConstraint(["line_id"], ["gov_production_lines.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("line_id", "revision", name="uq_gov_layout_revision"),
    )
    op.create_table(
        "gov_production_versions",
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("production_date", sa.Date(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("approved_by_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("source IN ('MANUAL','IMPORT','ERP','DEMO')", name="ck_gov_production_source"),
        sa.CheckConstraint("status <> 'APPROVED' OR approved_at IS NOT NULL", name="ck_gov_production_approval"),
        sa.CheckConstraint("status IN ('DRAFT','APPROVED','SUPERSEDED')", name="ck_gov_production_status"),
        sa.CheckConstraint("quantity >= 0 AND revision > 0", name="ck_gov_production_values"),
        sa.ForeignKeyConstraint(["approved_by_id"], ["user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["line_id"], ["gov_production_lines.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("line_id", "production_date", "revision", name="uq_gov_production_revision"),
    )
    op.create_index("ix_gov_production_date", "gov_production_versions", ["production_date", "line_id"], unique=False)
    op.create_index(
        "uq_gov_production_current",
        "gov_production_versions",
        ["line_id", "production_date"],
        unique=True,
        postgresql_where=sa.text("status = 'APPROVED'"),
        sqlite_where=sa.text("status = 'APPROVED'"),
    )
    op.create_table(
        "gov_report_versions",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("template_version", sa.String(length=80), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("revision > 0", name="ck_gov_report_revision"),
        sa.ForeignKeyConstraint(["report_id"], ["gov_reports.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["gov_dataset_snapshots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id", "revision", name="uq_gov_report_revision"),
    )
    op.create_table(
        "gov_review_decisions",
        sa.Column("occurrence_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("disposition", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("disposition IN ('REQUIRED','OPTIONAL','EXEMPT','UNDETERMINED')", name="ck_gov_decision_kind"),
        sa.ForeignKeyConstraint(["actor_id"], ["user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["occurrence_id"], ["scrap_occurrences.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["policy_id"], ["gov_review_policies.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_gov_decision_history", "gov_review_decisions", ["occurrence_id", "created_at"], unique=False)
    op.create_table(
        "gov_action_cases",
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["action_id"], ["gov_actions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["case_id"], ["gov_cases.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id", "case_id", name="uq_gov_action_case"),
    )
    op.create_table(
        "gov_analysis_versions",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("content", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('ACTION_REQUIRED','MONITOR_ONLY','NO_ACTION_REQUIRED')", name="ck_gov_analysis_decision"
        ),
        sa.CheckConstraint("revision > 0", name="ck_gov_analysis_revision"),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["case_id"], ["gov_cases.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "revision", name="uq_gov_analysis_revision"),
    )
    op.create_table(
        "gov_audit_findings",
        sa.Column("cycle_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["action_id"], ["gov_actions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["cycle_id"], ["gov_audit_cycles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_gov_finding_cycle", "gov_audit_findings", ["cycle_id", "status"], unique=False)
    op.create_table(
        "gov_case_occurrences",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("occurrence_id", sa.Uuid(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("unlinked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["gov_cases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["occurrence_id"], ["scrap_occurrences.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "occurrence_id", name="uq_gov_case_occurrence"),
    )
    op.create_index(
        "uq_gov_occurrence_primary_case",
        "gov_case_occurrences",
        ["occurrence_id"],
        unique=True,
        postgresql_where=sa.text("is_primary AND unlinked_at IS NULL"),
        sqlite_where=sa.text("is_primary AND unlinked_at IS NULL"),
    )
    op.create_table(
        "gov_effectiveness_checks",
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("measurement", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("evaluator_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("result IN ('EFFECTIVE','INEFFECTIVE','INCONCLUSIVE')", name="ck_gov_effectiveness_result"),
        sa.ForeignKeyConstraint(["action_id"], ["gov_actions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["evaluator_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_gov_effectiveness_action", "gov_effectiveness_checks", ["action_id", "created_at"], unique=False)
    op.create_table(
        "gov_export_jobs",
        sa.Column("report_version_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("options", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("format IN ('PDF','PPTX','CSV','XLSX')", name="ck_gov_export_format"),
        sa.CheckConstraint("status IN ('QUEUED','RUNNING','COMPLETED','FAILED')", name="ck_gov_export_status"),
        sa.ForeignKeyConstraint(["report_version_id"], ["gov_report_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index("ix_gov_export_queue", "gov_export_jobs", ["status", "created_at"], unique=False)
    op.create_table(
        "gov_snapshot_items",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("occurrence_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("frozen_values", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["occurrence_id"], ["scrap_occurrences.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["gov_dataset_snapshots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["transaction_id"], ["scrap_transactions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "occurrence_id", name="uq_gov_snapshot_occurrence"),
    )
    op.create_table(
        "gov_workstations",
        sa.Column("layout_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["layout_id"], ["gov_line_layouts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("layout_id", "code", name="uq_gov_station_code"),
    )
    op.create_table(
        "gov_artifacts",
        sa.Column("export_job_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("size_bytes > 0", name="ck_gov_artifact_size"),
        sa.ForeignKeyConstraint(["export_job_id"], ["gov_export_jobs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("export_job_id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_table(
        "gov_report_analyses",
        sa.Column("report_version_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["gov_analysis_versions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["report_version_id"], ["gov_report_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_version_id", "analysis_id", name="uq_gov_report_analysis"),
    )
    # ### end Alembic commands ###


def upgrade() -> None:
    # Legacy local bootstrap uses create_all before Alembic. Accept a complete
    # baseline, but never silently bless a partially created governance schema.
    expected = {
        "gov_factories",
        "gov_production_lines",
        "gov_line_layouts",
        "gov_workstations",
        "gov_production_versions",
        "gov_review_policies",
        "gov_review_decisions",
        "gov_cases",
        "gov_case_occurrences",
        "gov_analysis_versions",
        "gov_actions",
        "gov_action_cases",
        "gov_effectiveness_checks",
        "gov_dataset_snapshots",
        "gov_snapshot_items",
        "gov_reports",
        "gov_report_versions",
        "gov_report_analyses",
        "gov_export_jobs",
        "gov_artifacts",
        "gov_audit_cycles",
        "gov_audit_findings",
        "gov_audit_events",
        "gov_outbox_events",
        "gov_consumer_receipts",
    }
    existing = set(sa.inspect(op.get_bind()).get_table_names()) & expected
    if existing and existing != expected:
        raise RuntimeError("Partial governance schema: reconcile before migrating")
    if not existing:
        _create_tables()
    if op.get_bind().dialect.name == "postgresql":
        _install_guards()


def _install_guards() -> None:
    op.execute("""
    CREATE OR REPLACE FUNCTION gov_guard_report_analysis() RETURNS trigger AS $$
    BEGIN
      IF TG_OP <> 'INSERT' THEN
        PERFORM 1 FROM gov_report_versions WHERE id = OLD.report_version_id FOR UPDATE;
        IF EXISTS (SELECT 1 FROM gov_report_versions WHERE id = OLD.report_version_id AND published_at IS NOT NULL) THEN
          RAISE EXCEPTION 'Report edition is published';
        END IF;
      END IF;
      IF TG_OP <> 'DELETE' THEN
        PERFORM 1 FROM gov_report_versions WHERE id = NEW.report_version_id FOR UPDATE;
        IF EXISTS (SELECT 1 FROM gov_report_versions WHERE id = NEW.report_version_id AND published_at IS NOT NULL) THEN
          RAISE EXCEPTION 'Report edition is published';
        END IF;
        IF NOT EXISTS (
          SELECT 1 FROM gov_report_versions v JOIN gov_reports r ON r.id = v.report_id
          JOIN gov_analysis_versions a ON a.id = NEW.analysis_id
          JOIN gov_cases c ON c.id = a.case_id
          WHERE v.id = NEW.report_version_id AND r.factory_id = c.factory_id
        ) THEN RAISE EXCEPTION 'Report and analysis belong to different factories'; END IF;
        RETURN NEW;
      END IF;
      RETURN OLD;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("DROP TRIGGER IF EXISTS guard_report_analysis ON gov_report_analyses")
    op.execute(
        "CREATE TRIGGER guard_report_analysis BEFORE INSERT OR UPDATE OR DELETE ON gov_report_analyses "
        "FOR EACH ROW EXECUTE FUNCTION gov_guard_report_analysis()"
    )
    op.execute("""
    CREATE OR REPLACE FUNCTION gov_guard_report_scope() RETURNS trigger AS $$
    BEGIN
      PERFORM 1 FROM gov_dataset_snapshots WHERE id = NEW.snapshot_id FOR UPDATE;
      IF NOT EXISTS (
        SELECT 1 FROM gov_reports r JOIN gov_dataset_snapshots s ON s.factory_id = r.factory_id
        WHERE r.id = NEW.report_id AND s.id = NEW.snapshot_id
          AND (NEW.published_at IS NULL OR s.sealed_at IS NOT NULL)
      ) THEN RAISE EXCEPTION 'Report requires same-factory snapshot, sealed before publication'; END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("DROP TRIGGER IF EXISTS guard_report_scope ON gov_report_versions")
    op.execute(
        "CREATE TRIGGER guard_report_scope BEFORE INSERT OR UPDATE ON gov_report_versions "
        "FOR EACH ROW EXECUTE FUNCTION gov_guard_report_scope()"
    )
    op.execute("""
    CREATE OR REPLACE FUNCTION gov_guard_action_scope() RETURNS trigger AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM gov_actions a JOIN gov_cases c ON c.factory_id = a.factory_id
        WHERE a.id = NEW.action_id AND c.id = NEW.case_id
      ) THEN RAISE EXCEPTION 'Action and case belong to different factories'; END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("DROP TRIGGER IF EXISTS guard_action_scope ON gov_action_cases")
    op.execute(
        "CREATE TRIGGER guard_action_scope BEFORE INSERT OR UPDATE ON gov_action_cases "
        "FOR EACH ROW EXECUTE FUNCTION gov_guard_action_scope()"
    )
    op.execute("""
    CREATE OR REPLACE FUNCTION gov_guard_immutable() RETURNS trigger AS $$
    BEGIN
      IF TG_ARGV[0] = 'always' OR
         (TG_ARGV[0] = 'sealed_at' AND OLD.sealed_at IS NOT NULL) THEN
        RAISE EXCEPTION 'Immutable governance record: %', TG_TABLE_NAME;
      END IF;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    # Separate functions avoid accessing fields absent from a table's row type.
    op.execute("""
    CREATE OR REPLACE FUNCTION gov_guard_published() RETURNS trigger AS $$
    BEGIN
      IF OLD.published_at IS NOT NULL THEN
        RAISE EXCEPTION 'Published version is immutable: %', TG_TABLE_NAME;
      END IF;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE OR REPLACE FUNCTION gov_guard_append_only() RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'Append-only governance record: %', TG_TABLE_NAME;
    END;
    $$ LANGUAGE plpgsql;
    """)
    for table in ("gov_audit_events", "gov_review_decisions", "gov_effectiveness_checks"):
        op.execute(f"DROP TRIGGER IF EXISTS guard_immutable ON {table}")
        op.execute(
            f"CREATE TRIGGER guard_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION gov_guard_append_only()"
        )
    for table in ("gov_analysis_versions", "gov_report_versions"):
        op.execute(f"DROP TRIGGER IF EXISTS guard_immutable ON {table}")
        op.execute(
            f"CREATE TRIGGER guard_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION gov_guard_published()"
        )
    op.execute("DROP TRIGGER IF EXISTS guard_immutable ON gov_dataset_snapshots")
    op.execute(
        "CREATE TRIGGER guard_immutable BEFORE UPDATE OR DELETE ON gov_dataset_snapshots "
        "FOR EACH ROW EXECUTE FUNCTION gov_guard_immutable('sealed_at')"
    )
    op.execute("""
    CREATE OR REPLACE FUNCTION gov_guard_snapshot_item() RETURNS trigger AS $$
    DECLARE parent_id uuid;
    BEGIN
      IF TG_OP <> 'INSERT' THEN
        PERFORM 1 FROM gov_dataset_snapshots WHERE id = OLD.snapshot_id FOR UPDATE;
        IF EXISTS (SELECT 1 FROM gov_dataset_snapshots WHERE id = OLD.snapshot_id AND sealed_at IS NOT NULL) THEN
          RAISE EXCEPTION 'Snapshot is sealed';
        END IF;
      END IF;
      IF TG_OP <> 'DELETE' THEN
        parent_id := NEW.snapshot_id;
        PERFORM 1 FROM gov_dataset_snapshots WHERE id = parent_id FOR UPDATE;
        IF EXISTS (SELECT 1 FROM gov_dataset_snapshots WHERE id = parent_id AND sealed_at IS NOT NULL) THEN
          RAISE EXCEPTION 'Snapshot is sealed';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM scrap_transactions
                       WHERE id = NEW.transaction_id AND occurrence_id = NEW.occurrence_id) THEN
          RAISE EXCEPTION 'Transaction does not belong to snapshot occurrence';
        END IF;
        RETURN NEW;
      END IF;
      RETURN OLD;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("DROP TRIGGER IF EXISTS guard_snapshot_item ON gov_snapshot_items")
    op.execute(
        "CREATE TRIGGER guard_snapshot_item BEFORE INSERT OR UPDATE OR DELETE ON gov_snapshot_items "
        "FOR EACH ROW EXECUTE FUNCTION gov_guard_snapshot_item()"
    )
    op.execute("""
    CREATE OR REPLACE FUNCTION gov_guard_production() RETURNS trigger AS $$
    BEGIN
      IF OLD.status IN ('APPROVED', 'SUPERSEDED') THEN
        IF TG_OP = 'UPDATE' AND OLD.status = 'APPROVED' AND NEW.status = 'SUPERSEDED'
           AND (to_jsonb(NEW) - 'status') = (to_jsonb(OLD) - 'status') THEN RETURN NEW; END IF;
        RAISE EXCEPTION 'Approved production requires a new revision';
      END IF;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("DROP TRIGGER IF EXISTS guard_production ON gov_production_versions")
    op.execute(
        "CREATE TRIGGER guard_production BEFORE UPDATE OR DELETE ON gov_production_versions "
        "FOR EACH ROW EXECUTE FUNCTION gov_guard_production()"
    )


def downgrade() -> None:
    op.drop_table("gov_report_analyses")
    op.drop_table("gov_artifacts")
    op.drop_table("gov_workstations")
    op.drop_table("gov_snapshot_items")
    op.drop_table("gov_export_jobs")
    op.drop_table("gov_effectiveness_checks")
    op.drop_table("gov_case_occurrences")
    op.drop_table("gov_audit_findings")
    op.drop_table("gov_analysis_versions")
    op.drop_table("gov_action_cases")
    op.drop_table("gov_review_decisions")
    op.drop_table("gov_report_versions")
    op.drop_table("gov_production_versions")
    op.drop_table("gov_line_layouts")
    op.drop_table("gov_cases")
    op.drop_table("gov_audit_events")
    op.drop_table("gov_actions")
    op.drop_table("gov_review_policies")
    op.drop_table("gov_reports")
    op.drop_table("gov_production_lines")
    op.drop_table("gov_dataset_snapshots")
    op.drop_table("gov_consumer_receipts")
    op.drop_table("gov_audit_cycles")
    op.drop_table("gov_outbox_events")
    op.drop_table("gov_factories")
    if op.get_bind().dialect.name == "postgresql":
        for name in (
            "gov_guard_report_analysis",
            "gov_guard_report_scope",
            "gov_guard_action_scope",
            "gov_guard_immutable",
            "gov_guard_published",
            "gov_guard_append_only",
            "gov_guard_snapshot_item",
            "gov_guard_production",
        ):
            op.execute(f"DROP FUNCTION IF EXISTS {name}()")
